MyApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MyApp import views
from django.contrib.auth.views import LoginView,LogoutView

app_name="MyApp"

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('afterlogin_view/', views.afterlogin_view, name="afterlogin_view"),
    path('Covid19/', views.Covid19, name="Covid19"),
    path('CentersofExcellence/', views.CentersofExcellence, name="CentersofExcellence"),
    path('home_book_appointment/', views.home_book_appointment, name="home_book_appointment"),
    path('CovidTesting/', views.CovidTesting, name="CovidTesting"),
    path('CovidVaccination/', views.CovidVaccination, name="CovidVaccination"),
    path('CovidResources/', views.CovidResources, name="CovidResources"),
    path('Covid19Treatment/', views.Covid19Treatment, name="Covid19Treatment"),
    path('Covid19VaccineMyths/', views.Covid19VaccineMyths, name="Covid19VaccineMyths"),
    path('Covid19Symptoms/', views.Covid19Symptoms, name="Covid19Symptoms"),
    path('logout/', LogoutView.as_view(template_name='MyApp/home.html'),name='logout'),


    path('patientlogin/', views.PatientLogin, name="patientlogin"),
    path('patientsignup/', views.PatientSignUp, name="patientsignup"),
    path('patient_dashboard/', views.patient_dashboard, name="patient_dashboard"),
    path('patient_book_appointment/', views.patient_book_appointment, name="patient_book_appointment"),
    path('patient_my_appointment/', views.patient_my_appointment, name="patient_my_appointment"),
    path('patient_invoice/', views.patient_invoice, name="patient_invoice"),
    path('wait_approval/', views.wait_approval, name="wait_approval"), 


    path('doctorlogin/', views.DoctorLogin, name="doctorlogin"),
    path('doctorsignup/', views.DoctorSignUp, name="doctorsignup"),
    path('doctor_dashboard/', views.doctor_dashboard, name="doctor_dashboard"),
    path('doctor_wait_approval/', views.doctor_wait_approval, name="doctor_wait_approval"),
    path('doctor_patient/', views.doctor_patient, name="doctor_patient"),  
    path('doctor_appointment/', views.doctor_appointment, name="doctor_appointment"),
    path('doctor_view_patient/', views.doctor_view_patient, name="doctor_view_patient"),
    path('doctor_view_discharged_patient/', views.doctor_view_discharged_patient, name="doctor_view_discharged_patient"), 
    path('doctor_view_appointment/', views.doctor_view_appointment, name="doctor_view_appointment"),
    path('doctor_delete_appointment/', views.doctor_delete_appointment, name="doctor_delete_appointment"),


    path('adminlogin/', views.AdminLogin, name="adminlogin"),
    path('adminsignup/', views.AdminSignUp, name="adminsignup"),
    path('admin_dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('admin_patient/', views.admin_patient, name="admin_patient"),
    path('admin_patient_record/', views.admin_patient_record, name="admin_patient_record"),
    path('admin_admit_patient/', views.admin_admit_patient, name="admin_admit_patient"),    
    path('admin_approve_patient/', views.admin_approve_patient,name="admin_approve_patient"),
    path('admin_discharge_patient/', views.admin_discharge_patient,name='admin_discharge_patient'),
    path('approve_patient/<int:pk>', views.approve_patient,name='approve_patient'),
    path('reject_patient/<int:pk>', views.reject_patient,name='reject_patient'),
    path('update_patient/<int:pk>', views.update_patient,name='update_patient'),
    path('delete_patient/<int:pk>', views.delete_patient,name='delete_patient'),
    path('discharge_patient/<int:pk>', views.discharge_patient,name='discharge_patient'),
    path('download_pdf/<int:pk>', views.download_pdf,name='download_pdf'),

    path('admin_doctor/', views.admin_doctor, name="admin_doctor"),
    path('admin_doctor_record/', views.admin_doctor_record,name="admin_doctor_record"),
    path('admin_add_doctor/', views.admin_add_doctor,name="admin_add_doctor"),
    path('admin_approve_doctor/', views.admin_approve_doctor,name="admin_approve_doctor"),
    path('admin_doctor_specialization/', views.admin_doctor_specialization,name="admin_doctor_specialization"),
    path('update_doctor/<int:pk>', views.update_doctor,name='update_doctor'),
    path('delete_doctor/<int:pk>', views.delete_doctor,name='delete_doctor'),
    path('approve_doctor/<int:pk>', views.approve_doctor,name='approve_doctor'),
    path('reject_doctor/<int:pk>', views.reject_doctor,name='reject_doctor'),

    path('admin_appointment/', views.admin_appointment, name="admin_appointment"),
    path('admin_view_appointment/', views.admin_view_appointment, name="admin_view_appointment"),
    path('admin_add_appointment/', views.admin_add_appointment, name="admin_add_appointment"),
    path('admin_approve_appointment/', views.admin_approve_appointment, name="admin_approve_appointment"),
    path('approve_appointment/<int:pk>', views.approve_appointment,name='approve_appointment'),
    path('reject_appointment/<int:pk>', views.reject_appointment,name='reject_appointment'),
    path('delete_appointment/<int:pk>', views.delete_appointment,name='delete_appointment'),
]

MyProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from MyApp import views

app_name="MyApp"

urlpatterns = [
    path('', include('MyApp.urls')),
    path('home/', include('MyApp.urls')),
    path('about/', include('MyApp.urls')),
    path('afterlogin_view/', include('MyApp.urls')),
    path('Covid19/', include('MyApp.urls')),
    path('CentersofExcellence/', include('MyApp.urls')),
    path('home_book_appointment/', include('MyApp.urls')),
    path('CovidTesting/', include('MyApp.urls')),
    path('CovidVaccination/', include('MyApp.urls')),
    path('CovidResources/', include('MyApp.urls')),
    path('Covid19Treatment/', include('MyApp.urls')),
    path('Covid19VaccineMyths/', include('MyApp.urls')),
    path('Covid19Symptoms/', include('MyApp.urls')),
    path('logout/', include('MyApp.urls')),


    path('patientlogin/', include('MyApp.urls')),
    path('patientsignup/', include('MyApp.urls')),
    path('patient_dashboard/', include('MyApp.urls')),
    path('patient_book_appointment/', include('MyApp.urls')),
    path('patient_my_appointment/', include('MyApp.urls')),
    path("patient_invoice/", include('MyApp.urls')),
    path("patient_covid19/", include('MyApp.urls')),
    path("wait_approval/", include('MyApp.urls')),


    path('doctorlogin/', include('MyApp.urls')),
    path('doctorsignup/', include('MyApp.urls')),
    path('doctor_dashboard/', include('MyApp.urls')),
    path("doctor_wait_approval/", include('MyApp.urls')),
    path("doctor_patient/", include('MyApp.urls')),
    path("doctor_patient/", include('MyApp.urls')),
    path("doctor_appointment/", include('MyApp.urls')),
    path("doctor_view_patient/", include('MyApp.urls')),
    path("doctor_view_discharged_patient/", include('MyApp.urls')),
    path('doctor_view_appointment/', include('MyApp.urls')),
    path('doctor_delete_appointment/', include('MyApp.urls')),


    path('adminlogin/', include('MyApp.urls')),
    path('adminsignup/', include('MyApp.urls')),
    path('admin_dashboard/', include('MyApp.urls')),
    path('admin_patient/', include('MyApp.urls')),
    path('admin_patient_record/', include('MyApp.urls')),
    path('admin_admit_patient/', include('MyApp.urls')),
    path('admin_approve_patient/', include('MyApp.urls')),
    path('approve_patient/<int:pk>', include('MyApp.urls')),
    path('admin_discharge_patient/', include('MyApp.urls')),
    path('discharge_patient/', include('MyApp.urls')),
    path('admin_appointment/', include('MyApp.urls')),
    path('update_patient/<int:pk>', include('MyApp.urls')),
    path('delete_patient/', include('MyApp.urls')),
    path('download_pdf/<int:pk>', include('MyApp.urls')),

    path('admin_doctor/', include('MyApp.urls')),
    path('admin_doctor_record/', include('MyApp.urls')),
    path('admin_add_doctor/', include('MyApp.urls')),
    path('admin_approve_doctor/', include('MyApp.urls')),
    path('approve_doctor/<int:pk>', include('MyApp.urls')),
    path('reject_doctor/<int:pk>', include('MyApp.urls')),
    path('admin_doctor_specialization/', include('MyApp.urls')),    
    path('update_doctor/<int:pk>', include('MyApp.urls')),
    path('delete_doctor/', include('MyApp.urls')),
    
    path('admin_appointment/', include('MyApp.urls')),
    path('admin_view_appointment/', include('MyApp.urls')),
    path('admin_add_appointment/', include('MyApp.urls')),
    path('admin_approve_appointment/', include('MyApp.urls')),  
    path('approve_appointment/<int:pk>',include('MyApp.urls')),
    path('reject_appointment/<int:pk>', include('MyApp.urls')), 
    path('delete_appointment/<int:pk>', include('MyApp.urls')),  

    path('admin/', admin.site.urls),
]

MyApp/models.py
from django.db import models
from django.contrib.auth.models import User

GENDER = [
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
]
Time = [
    ("10:00 A.M", "10:00 A.M"),
    ("10:30 A.M", "10:30 A.M"),
    ("11:00 A.M", "11:00 A.M"),
    ("11:30 A.M", "11:30 A.M"),
    ("12:00 P.M", "12:00 P.M"),
    ("12:30 P.M", "12:30 P.M"),
    ("01:00 P.M", "01:00 P.M"),
    ("01:30 P.M", "01:30 P.M"),
    ("05:00 P.M", "05:00 P.M"),
    ("05:30 P.M", "05:30 P.M"),
    ("06:00 P.M", "06:00 P.M"),
    ("06:30 P.M", "06:30 P.M"),
    ("07:00 P.M", "07:00 P.M"),
    ("07:30 P.M", "07:30 P.M"),
    ("08:00 P.M", "08:00 P.M"),
    ("08:30 P.M", "08:30 P.M"),
]


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Patient_First_Name = models.CharField(max_length=50, default="")
    Patient_Last_Name = models.CharField(max_length=50, default="")
    gender = models.CharField(max_length=10, choices=GENDER)
    contact = models.CharField(max_length=10)
    address = models.CharField(max_length=350)
    symptoms = models.CharField(max_length=500, default="")
    status = models.BooleanField(default=False)
    admitDate = models.DateField(auto_now=True)
    assignedDoctorId = models.PositiveIntegerField(null=True)

    @property
    def get_name(self):
        return self.Patient_First_Name + " " + self.Patient_Last_Name

    @property
    def get_id(self):
        return self.id

    def __str__(self):
        return self.Patient_First_Name + " " + self.Patient_Last_Name




departments = [('Cardiologist', 'Cardiologist'),
               ('Dermatologists', 'Dermatologists'),
               ('General Physician', 'General Physician'),
               ('NeuroSurgeon', 'NeuroSurgeon'),
               ('GastroEntologists', 'GastroEntologists'),
               ('Pediatrician', 'Pediatrician'),
               ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'),
               ('Allergists/Immunologists', 'Allergists/Immunologists'),
               ('Anesthesiologists', 'Anesthesiologists'),
               ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')
               ]


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Doctor_First_Name = models.CharField(max_length=50, default="")
    Doctor_Last_Name = models.CharField(max_length=50, default="")
    gender = models.CharField(max_length=10, choices=GENDER, default="")
    address = models.CharField(max_length=40)
    contact = models.CharField(max_length=10, null=True)
    department = models.CharField(max_length=50, choices=departments, default='')
    status = models.BooleanField(default=False)

    @property
    def get_name(self):
        return self.Doctor_First_Name + " " + self.Doctor_Last_Name

    @property
    def get_id(self):
        return self.id

    def __str__(self):
        return "{} ({})".format(self.Doctor_First_Name + " " + self.Doctor_Last_Name, self.department)




class Appointment(models.Model):
    patientId = models.PositiveIntegerField(null=True)
    doctorId = models.PositiveIntegerField(null=True)
    patientName = models.CharField(max_length=40, null=True)
    doctorName = models.CharField(max_length=40, null=True)
    appointmentDate = models.DateField(null=False)
    description = models.TextField(max_length=500)
    status = models.BooleanField(default=False)
    time = models.CharField(max_length=10, choices=Time, default="")

    @property
    def get_docId(self):
        return self.doctorId

    @property
    def get_description(self):
        return self.description

    @property
    def get_status(self):
        return self.status



class PatientDischarge(models.Model):
    patientId = models.PositiveIntegerField(null=True)
    patientName = models.CharField(max_length=40)
    assignedDoctorName = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20, null=True)
    symptoms = models.CharField(max_length=100, null=True)
    admitDate = models.DateField(null=False)
    releaseDate = models.DateField(null=False)
    daySpent = models.PositiveIntegerField(null=False)
    roomCharge = models.PositiveIntegerField(null=False, default=0)
    medicineCost = models.PositiveIntegerField(null=False, default=0)
    doctorFee = models.PositiveIntegerField(null=False, default=0)
    OtherCharge = models.PositiveIntegerField(null=False, default=0)
    total = models.PositiveIntegerField(null=False)

MyApp/forms.py
from django import forms
from django.contrib.auth.models import User
from MyApp.models import Patient, Doctor, Appointment


class DateInput(forms.DateInput):
    input_type = 'date'

#_____________________________________________________________________________________________________________________

GENDER =(
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),
)
Time = [
    ("10:00 A.M","10:00 A.M"),
    ("10:30 A.M","10:30 A.M"),
    ("11:00 A.M","11:00 A.M"),
    ("11:30 A.M","11:30 A.M"),
    ("12:00 P.M","12:00 P.M"),
    ("12:30 P.M","12:30 P.M"),
    ("01:00 P.M","01:00 P.M"),
    ("01:30 P.M","01:30 P.M"),
    ("05:00 P.M","05:00 P.M"),
    ("05:30 P.M","05:30 P.M"),
    ("06:00 P.M","06:00 P.M"),
    ("06:30 P.M","06:30 P.M"),
    ("07:00 P.M","07:00 P.M"),
    ("07:30 P.M","07:30 P.M"),
    ("08:00 P.M","08:00 P.M"),
    ("08:30 P.M","08:30 P.M"),
]

class PatientUserInfo(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput()) #hash out the password
    
    class Meta():
        model = User
        fields = ('username','email','password')

class PatientSignUpForm(forms.ModelForm):
    class Meta():
        model = Patient
        fields = ('Patient_First_Name','Patient_Last_Name','gender', 'contact', 'address')        
#_____________________________________________________________________________________________________________________

class DoctorUserInfo(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput()) #hash out the password
    
    class Meta():
        model = User
        fields = ('username','password')

class DoctorSignUpForm(forms.ModelForm):
    class Meta():
        model = Doctor
        fields = ('Doctor_First_Name','Doctor_Last_Name','gender','department', 'contact', 'address')
        
#_____________________________________________________________________________________________________________________
class AdminUserInfo(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput()) #hash out the password
    
    class Meta():
        model = User
        fields = ('username','password')

class AdminSignUpForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('first_name','last_name','username','password')
#_____________________________________________________________________________________________________________________

class AppointmentForm(forms.ModelForm):
    doctorId=forms.ModelChoiceField(queryset=Doctor.objects.all().filter(status=True),empty_label="Doctor Name and Department", to_field_name="user_id")
    patientId=forms.ModelChoiceField(queryset=Patient.objects.all().filter(status=True),empty_label="Patient Name", to_field_name="user_id")
    appointmentDate = forms.DateField(widget = forms.SelectDateWidget())
    class Meta:
        model=Appointment
        fields=['appointmentDate','time','description']

class PatientAppointmentForm(forms.ModelForm):
    doctorId=forms.ModelChoiceField(queryset=Doctor.objects.all().filter(status=True),empty_label="Doctor Name and Department", to_field_name="user_id")
    
    appointmentDate = forms.DateField(widget = forms.SelectDateWidget())
    class Meta:
        model=Appointment
        fields=['appointmentDate','time','description']

#_____________________________________________________________________________________________________________________

templates/MyApp/Covid19.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{%  static 'css/homestyle.css' %}"/>  
        <title>Covid-19 · Ask A Doctor</title>
             
    </head>
    <body>
            <div class="container" style="font-family: serif" >
                {% include 'MyApp/web_head.html' %}
                {% include 'MyApp/navbar.html' %}

                  <div class="card-container">
                      <div class="cards">
                          <div class="card">
                              <h2 class="card-title">Testing</h2>
                              <a href="{% url 'MyApp:CovidTesting' %}">
                              <img src="https://prsciencetrust.org/wp-content/uploads/2021/03/shutterstock_1876606570.jpeg" alt="">
                              </a>
                          </div>
                          <div class="card">
                              <h2 class="card-title">Vaccination</h2>
                              <a href="{% url 'MyApp:CovidVaccination' %}">  
                              <img src="https://cdn.dnaindia.com/sites/default/files/styles/full/public/2021/04/30/972022-covid-vaccine.jpg" alt="">
                              </a>
                          </div>
                          <div class="card">
                              <h2 class="card-title">Resources</h2>
                              
                              <a href="{% url 'MyApp:CovidResources' %}">         
                              <img src="https://thefederal.com/file/2020/06/interior-of-new-empty-hospital-room-picture-id1153684245-696x435.jpg" alt="">       
                              </a>
                          </div>
                      </div>
                  </div>
              <br><br><br><br><br>
              <h1 style="padding-left:50px;">Covid-19 information</h1>
              <div class="blog-post" style="padding:20px;">
                <img src="https://apollohealthlib.blob.core.windows.net/health-library/2021/04/Treatments-for-Covid-19.jpg" width="300" height="200" id="hp" />
                    <h2 style="padding-top:10px;"> Treatments for Covid-19 </h2>   
                    <p>India is currently reeling under the impact of the second wave of COVID-19 pandemic 
                    that has led to an alarming surge in daily cases. Amid the massive surge in the COVID-19 
                    cases across India, people are looking out for tips on self-care and treatment options 
                    for people severely affected by COVID-19 disease.</p>

                    <div class="button">
                      <a style="background-color: #00b8b1;
                        color:white ;  
                        padding:12px;
                        width:75px;
                        border: none;
                        float:right;
                        border-radius: 5px; " href="{% url 'MyApp:Covid19Treatment'  %}">Read More</a>
                    
              </div>
            </div>
            <div class="blog-post" style="padding:20px;">
                <img src="https://apollohealthlib.blob.core.windows.net/health-library/2021/04/Common-COVID-19-Vaccine-Myths-1536x1024.jpg" width="300" height="200" id="hp" />
                    <h2 style="padding-top:10px;">Common Myths about the Covid-19 Vaccine</h2>   
                    <p>With the vaccination drive underway, it is important to dispel any myths about 
                    vaccines circulating in India. Lack of proper understanding and lack of exposure
                     to the science behind the functioning of a vaccine can prove harmful to the many 
                     individuals who are withholding themselves from getting vaccinated. At the same time, 
                     it is essential to educate oneself about these vaccines from the right sources.</p>
                    <div class="button">
                      <a style="background-color: #00b8b1;
                        color:white ;  
                        padding:12px;
                        width:75px;
                        border: none;
                        float:right;
                        border-radius: 5px; " href="{% url 'MyApp:Covid19VaccineMyths'  %}">Read More</a>
              </div>
            </div>
            <div class="blog-post" style="padding:20px;">
                <img src="https://apollohealthlib.blob.core.windows.net/health-library/2021/04/New-symptoms-of-COVID-19-1536x1024.jpg" width="300" height="200" id="hp" />
                    <h2 style="padding-top:10px;"> New Covid-19 Symptoms </h2>   
                    <p>Every day, COVID-19 is in the news, showing new symptoms or 
                    variants affecting the human race. Thus, we need to reacquaint ourselves with all the essential 
                    information we can get regarding the spread, the second wave, or new variants.</p>
                    <div class="button">
                      <a style="background-color: #00b8b1;
                        color:white ;  
                        padding:12px;
                        width:75px;
                        border: none;
                        float:right;
                        border-radius: 5px; " href="{% url 'MyApp:Covid19Symptoms'  %}">Read More</a>
              </div>
            </div>
            </body>
    <style>


.card-container {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

.cards {
  width: 100%;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
}

.card {
  margin: 40px;
  position: relative;
  max-width: 350px;
  max-height: 350px;
  box-shadow: 0 40px 60px -6px rgba(0, 0, 0, 0.6);
  border-radius:25px;
}
.card:hover{
    transform: scale(1.03);
}

.card-title {
  display: block;
  text-align: center;
  color: black;
  padding: 2%;
}


.card img {
  width: 100%;
  height: 98%;
  object-fit: cover;
  display: block;
  position: relative;
  border-bottom-right-radius: 25px;
  border-bottom-left-radius: 25px;
}

.blog-post{
  margin-left:3%;
  width:90%;
  height:200px;
  background-color: #f9f9f9;
  margin-bottom:30px;
}
#hp{
    float: left;    
    margin: 0 0 0 15px;
    padding-right:50px;
}


</style>
</html>

templates/MyApp/adminlogin.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{%  static 'css/loginform.css' %}"/> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> 
        <title>Admin Login · Ask A Doctor</title>
             
    </head>
    <body >
        <div class="container" style="align-items:center">
            <div class="name">  
            </div>
            <div class="content-box">
                <div class="content-main">
                    <div class="login-form">
                        <h1>Admin Login</h1>
                        <h4>New Admin? <a href="{% url 'MyApp:adminsignup' %}">Register Here!</a></h4><br>
                         <form action="{% url 'MyApp:adminlogin' %}" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <label for="username">Username:</label>
                            <input type="username" name="username" placeholder="Enter Username">
                            <br><br>
                            <label for="password">Password:</label>
                            <input type="password" name="password"><br>
                        <input type="submit" class="btn-primary" value="Log in">
                        </form>
                    </div>
                    
                </div>
            </div>
       </div>
    </body>   
    <style> 
                body  
                {  
                    background-image:url("https://styledme.com/wp-content/uploads/2021/03/minimal-zoom-background.jpg"); 
                    background-repeat: no-repeat; 
                    max_width=100%;
                    max_height=100%;
                    background-size: cover;
                    position: relative;
                } 
            
    </style>  
</html>
            

templates/MyApp/doctor_appointment.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor · Home</title>
</head>
<body>  
    {% include 'MyApp/doctor_base.html' %}

    <h1>Appointments </h1>
    <div class="row">
    <div class="column">
        <div class="card" style="border-top: 5px solid rgb(255, 106, 106);">
        <h2><a href="{% url 'MyApp:doctor_view_appointment' %}" style="color:black">View Appointment</a></h2>
        </div>
    </div>

    <div class="column">
        <div class="card" style="border-top: 5px solid rgb(255, 178, 106);">
        <h2><a href="{% url 'MyApp:doctor_delete_appointment' %}" style="color:black">Delete Appointment</a></h2>
        </div>
    </div>
    </div>

</body>
</html>
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}
h1{
  margin-left: 300px;  
  text-align:center;
  margin-top: 120px;
}

/* Float four columns side by side */
.column {
  float: left;
  width: 50%;
  padding: 15px 15px;
}

/* Remove extra left and right margins, due to padding */
.row {
  margin-top: 65px;
  margin-left: 350px;
  margin-right: 60px;
  }

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: white;
}

.card:hover {
  background-color:#f9f9f9;
}
</style>

templates/MyApp/home_book_appointment.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{%  static 'css/homestyle.css' %}"/>  
        <title>Home · Ask A Doctor</title>
             
    </head>
    <body>
            <div class="container" style="font-family: serif" >
                {% include 'MyApp/web_head.html' %}
                {% include 'MyApp/navbar.html' %}
        
            <h2 style="margin:30px; text-align:center"><a href="{% url 'MyApp:patientlogin' %}" >Login Here to Book Appointment</a></h2>

        </div>
        </body>
        </html>